/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CCountInput: typeof import('./components/CCountInput/index.vue')['default']
    CMpHtml: typeof import('./components/CMpHtml/index.vue')['default']
    copy: typeof import('./components/VCountInput copy/index.vue')['default']
    CZPaging: typeof import('./components/CZPaging/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
    VCountInput: typeof import('./components/VCountInput/index.vue')['default']
  }
}
